#!/bin/bash

## Full installation ############################################
##module load singularity
##BIN_VERSION="1.3.0"
##singularity pull docker://google/deepvariant:"${BIN_VERSION}"
#################################################################

#SBATCH -J ReSeq_deepvar

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=24
#SBATCH --mem=64G
#SBATCH --time=5-00:00:00

module load singularity

BIN_VER="1.3.0"
REF="~/Elephant_project/mEleMax1/intermediates/bionano/l2/l2_s1.fa"
BAM_DIR="~/Elephant_project/ReSeq/pilot/bam_dedup"
OUT_DIR="~/Elephant_project/ReSeq/pilot/vcf_deepvar"

cd $OUT_DIR

singularity run -B /scratch/ddepanis/:/scratch/ddepanis/ docker://google/deepvariant:"${BIN_VER}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref="${REF}" --reads="${BAM_DIR}"/21Nov94-DL001_S12_L002.rmd.bam --output_vcf="${OUT_DIR}"/21Nov94-DL001_S12_L002.vcf.gz --output_gvcf="${OUT_DIR}"/21Nov94-DL001_S12_L002.g.vcf.gz --intermediate_results_dir "${OUT_DIR}/intermediate_results_dir" --num_shards=24

export PATH=~/Software/anaconda3/bin:$PATH
source activate RESEQ_env

export TMPDIR="~/tmp"


echo ""
echo ". Starting Picard..."
echo ""

BAM_IN=$(ls ${OUT_DIR}/bam_sort/*.bam | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
BAM_NAME=$(basename $BAM_IN .bam)
cd ${OUT_DIR}/bam_dedup
picard -Xmx64g MarkDuplicates REMOVE_DUPLICATES=true ASSUME_SORTED=true VALIDATION_STRINGENCY=SILENT MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 INPUT=$BAM_IN OUTPUT=${BAM_NAME}.rmd.bam METRICS_FILE=${BAM_NAME}.rmd.bam.metrics TMP_DIR=~/tmp

echo ""
echo ". Indexing bam..."
echo ""

samtools index ${BAM_NAME}.rmd.bam

echo ""
echo ". Analyzing reference coverage..."
echo ""
