#!/bin/bash

## Full installation ############################################
##module load singularity
##BIN_VERSION="1.3.0"
##singularity pull docker://google/deepvariant:"${BIN_VERSION}"
#################################################################

#SBATCH -J ReSeq_deepvar

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=24
#SBATCH --mem=64G
#SBATCH --time=5-00:00:00

module load singularity

BIN_VER="1.3.0"
export TMPDIR="~/tmp"

echo ""
echo ". Starting Deepvariant..."
echo ""

cd $OUT_DIR
singularity run -B /scratch/ddepanis/:/scratch/ddepanis/ docker://google/deepvariant:"${BIN_VER}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref="${REF}" --reads="${BAM_DIR}"/21Nov94-DL001_S12_L002.rmd.bam --output_vcf="${OUT_DIR}"/21Nov94-DL001_S12_L002.vcf.gz --output_gvcf="${OUT_DIR}"/21Nov94-DL001_S12_L002.g.vcf.gz --intermediate_results_dir "${OUT_DIR}/tmp_dir" --num_shards=24

