#!/bin/bash

## Full installation ##########################
##conda create -n FASTP_env -c bioconda fastp
###############################################

#SBATCH -J ReSeq_fastp

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=3
#SBATCH --mem=9G
#SBATCH --time=12:00:00

export PATH=~/Software/anaconda3/bin:$PATH
source activate FASTP_env

READ_1=$(ls $FQ_DIR/*R1*.fastq.gz | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
READ_NAME=$(basename $READ_1 _R1_001.fastq.gz)

cd $OUT_DIR
fastp --in1 $READ_1 --in2 $FQ_DIR/${READ_NAME}_R2_001.fastq.gz --out1 $OUT_DIR/${READ_NAME}_R1.trimmed.fastq.gz --out2 $OUT_DIR/${READ_NAME}_R2.trimmed.fastq.gz -l 50 -h $OUT_DIR/${READ_NAME}.html -j $OUT_DIR/${READ_NAME}.fastp.json
