#!/bin/bash

#SBATCH -J ReSeq_map

#SBATCH --cpus-per-task=12
#SBATCH --mem=24G
#SBATCH --time=2-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate RESEQ_env

echo ""
echo ". Starting bowtie2 & samtools..."
echo ""

READ=$(ls ${TRIM_DIR}/*R1*.fq.gz | head -n ${SLURM_ARRAY_TASK_ID} | tail -n 1)
READ_NAME=$(basename ${READ} _R1.trimmed.fq.gz)

echo ". Bowtie2 mapping stats for sample ${READ_NAME}" > "${OUT_DIR}/3_bam_eval/${READ_NAME}.stats"
echo "" >> "${OUT_DIR}/3_bam_eval/${READ_NAME}.stats"

cd "${OUT_DIR}/1_bam_sort"
srun \
bowtie2 -p 12 -x "${OUT_DIR}/0_idx/${ASSEMBLY_NAME}" -1 ${READ} -2 "${TRIM_DIR}/${READ_NAME}_R2.trimmed.fq.gz" --no-unal --no-mixed --no-discordant 2>> "${OUT_DIR}/3_bam_eval/${READ_NAME}.stats" | samtools view -@ 6 -b -u | samtools sort -@ 6 -o "${OUT_DIR}/1_bam_sort/${READ_NAME}.bam"

echo ""
echo ". Indexing bam..."
echo ""

samtools index ${READ_NAME}.bam
