#!/bin/bash

## Full installation ############################################
##module load singularity
##BIN_VERSION="1.3.0"
##singularity pull docker://google/deepvariant:"${BIN_VERSION}"
#################################################################

#SBATCH -J ReSeq_deepvar

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=24
#SBATCH --mem=64G
#SBATCH --time=5-00:00:00

module load singularity

BIN_VER="1.3.0"
export TMPDIR="~/tmp"

echo ""
echo ". Starting Deepvariant..."
echo ""

BAM_IN=$(ls $BAM_DIR/*.rmd.bam | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
BAM_NAME=$(basename $BAM_IN .bam)
mkdir -p ${OUT_DIR}/tmp_dir/${BAM_NAME}
cd $OUT_DIR
singularity run -B /scratch/ddepanis/:/scratch/ddepanis/ docker://google/deepvariant:"${BIN_VER}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref="${REF}" --reads="${BAM_IN}" --output_vcf="${OUT_DIR}"/"${BAM_NAME}".vcf.gz --output_gvcf="${OUT_DIR}"/"${BAM_NAME}".g.vcf.gz --intermediate_results_dir "${OUT_DIR}/tmp_dir/"${BAM_NAME}" --num_shards=24

