#!/bin/bash

#SBATCH -J ReSeq_index

#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=6:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate RESEQ_env

echo ""
echo ". Reference indexing..."
echo ""

cd "${OUT_DIR}/0_idx"

if [[ "${ASSEMBLY##*.}" == "gz" ]]
then
        INTER=$(basename ${ASSEMBLY} .gz)
        ASSEMBLY_NAME=$(basename $INTER .${INTER##*.})
        gunzip -c ${ASSEMBLY} > "${ASSEMBLY_NAME}.fa"
elif  [[ "${ASSEMBLY##*.}" == "fa" ]] || [[ "${ASSEMBLY##*.}" == "fasta" ]]
then
        ASSEMBLY_NAME=$(basename $ASSEMBLY .${ASSEMBLY##*.})
        ln -s ${ASSEMBLY} "${ASSEMBLY_NAME}.fa"
else
        echo "Invalid reference extension name!"
fi

srun \
bowtie2-build --threads 2 ${ASSEMBLY} ${ASSEMBLY_NAME}

srun \
samtools faidx "${ASSEMBLY_NAME}.fa"
