#!/bin/bash

#SBATCH -J ReSeq_index

#SBATCH --cpus-per-task=4
#SBATCH --mem=48G
#SBATCH --time=6:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate RESEQ_env

echo ""
echo ". Reference indexing..."
echo ""

cd "${OUT_DIR}/0_idx"

if [[ "${ASSEMBLY##*.}" == "gz" ]]
then
        gunzip -c ${ASSEMBLY} > "${ASSEMBLY_NAME}.fa"
elif  [[ "${ASSEMBLY##*.}" == "fa" ]] || [[ "${ASSEMBLY##*.}" == "fasta" ]]
then
        ln -s ${ASSEMBLY} "${ASSEMBLY_NAME}.fa"
else
        echo "Invalid reference extension name!"
fi

bowtie2-build --threads 2 ${ASSEMBLY} ${ASSEMBLY_NAME}
samtools faidx ${ASSEMBLY}
