#SBATCH -J ReSeq_deepvar

#SBATCH --cpus-per-task=18
#SBATCH --mem=64G
#SBATCH --time=5-00:00:00

${SINGULARITY_LOAD}

BIN_VER="1.3.0"

echo ""
echo ". Starting Deepvariant..."
echo ""

REFERENCE=$(ls ${OUT_DIR}/0_idx/*.fa)
#BAM_IN=$(ls ${OUT_DIR}/2_bam_dedup/*.bam | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
BAM_IN=$(ls ${OUT_DIR}/3_bam_masked/*.masked.bam | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
BAM_NAME=$(basename $BAM_IN .bam)
mkdir -p "${TMPDIR}/${BAM_NAME}"
cd "$OUT_DIR/5_deepvar"
srun \
singularity run -B ${BIND_DIR}:${BIND_DIR} docker://google/deepvariant:"${BIN_VER}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref="${REFERENCE}" --reads="${BAM_IN}" --output_vcf="${OUT_DIR}/5_deepvar/${BAM_NAME}.vcf.gz" --output_gvcf="${OUT_DIR}/5_deepvar/${BAM_NAME}.g.vcf.gz" --intermediate_results_dir="${TMPDIR}/${BAM_NAME}" --num_shards=18
