#!/bin/bash

#SBATCH -J ReSeq_map

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=24
#SBATCH --mem=64G
#SBATCH --time=5-00:00:00

export PATH=~/Software/anaconda3/bin:$PATH
source activate RESEQ_env

export TMPDIR="~/tmp"


echo ""
echo ". Starting bowtie2 & samtools..."
echo ""

READ=$(ls $FQ_DIR/*R1*.fq.gz | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
READ_NAME=$(basename $READ _R1.trimmed.fq.gz)
cd ${OUT_DIR}/1_bam_sort
bowtie2 -p 12 -x ${OUT_DIR}/0_idx/${ASSEMBLY_NAME} -1 $READ -2 ${FQ_DIR}/${READ_NAME}_R2.trimmed.fq.gz --no-unal --no-mixed --no-discordant | samtools view -@ 6 -b -u | samtools sort -@ 6 -o ${OUT_DIR}/1_bam_sort/${READ_NAME}.bam

echo ""
echo ". Indexing bam..."
echo ""

samtools index ${READ_NAME}.bam

echo ""
echo ". Calculating mapping stats..."
echo ""

samtools flagstat ${READ_NAME}.bam
